import { DataTypes } from "sequelize";
import { sequelize } from "../db/db.js";

const ProductVariant = sequelize.define('ProductVariant', {
    id: {
        type: DataTypes.INTEGER,
        primaryKey: true,
        autoIncrement: true
    },
    product_id: {
        type: DataTypes.INTEGER,
        allowNull: false,
        comment: 'FK → products.id'
    },
    platform_variant_id: {
        type: DataTypes.STRING,
        allowNull: true,
        comment: 'Variant ID from Shopify or WooCommerce'
    },

    option1_name: {
        type: DataTypes.STRING,
        allowNull: true,
        comment: 'e.g. "Size"'
    },
    option1_value: {
        type: DataTypes.STRING,
        allowNull: true,
        comment: 'e.g. "Large"'
    },
    option2_name: {
        type: DataTypes.STRING,
        allowNull: true
    },
    option2_value: {
        type: DataTypes.STRING,
        allowNull: true
    },
    option3_name: {
        type: DataTypes.STRING,
        allowNull: true
    },
    option3_value: {
        type: DataTypes.STRING,
        allowNull: true
    },
    title: {
        type: DataTypes.STRING,
        allowNull: true,
        comment: 'Combined label, e.g. "Large / Red". Auto-generated by platforms'
    },

    price: {
        type: DataTypes.DECIMAL(12, 2),
        allowNull: true
    },
    compare_at_price: {
        type: DataTypes.DECIMAL(12, 2),
        allowNull: true
    },

    sku: {
        type: DataTypes.STRING,
        allowNull: true
    },
    inventory_quantity: {
        type: DataTypes.INTEGER,
        allowNull: true
    },
    inventory_policy: {
        type: DataTypes.STRING,
        allowNull: true
    },

    weight: {
        type: DataTypes.FLOAT,
        allowNull: true
    },
    weight_unit: {
        type: DataTypes.STRING(8),
        allowNull: true
    },
    requires_shipping: {
        type: DataTypes.BOOLEAN,
        defaultValue: true
    },
    taxable: {
        type: DataTypes.BOOLEAN,
        defaultValue: true
    },

    image_url: {
        type: DataTypes.STRING,
        allowNull: true
    },

    position: {
        type: DataTypes.INTEGER,
        allowNull: true,
        comment: 'Display order within the product'
    }
}, {
    tableName: 'product_variants',
    timestamps: true,
    createdAt: 'created_at',
    updatedAt: 'updated_at',
    indexes: [
        { unique: true, fields: ['product_id', 'platform_variant_id'], name: 'uq_product_variant' },
        { fields: ['product_id'] },
        { fields: ['sku'] }
    ]
});

export default ProductVariant;