import { colors, rounded, spacing, typography } from './designTokens';

export { colors, rounded, spacing, typography };

/** Light: airy background, white surfaces, saturated accent chips */
export const lightPalette = {
  background: colors.canvasTint,
  surface: colors.canvas,
  surfaceSoft: '#f1f5f9',
  fillInput: '#f1f5f9',
  primary: colors.primary,
  primarySoft: colors.primarySoft,
  accent: colors.legalLink,
  coral: colors.coral,
  coralSoft: colors.coralSoft,
  mint: colors.mint,
  mintSoft: colors.mintSoft,
  iris: colors.iris,
  irisSoft: colors.irisSoft,
  amber: colors.amber,
  amberSoft: colors.amberSoft,
  chipInactive: '#eef2ff',
  text: colors.ink,
  textMuted: colors.inkMuted,
  border: colors.hairline,
  success: colors.success,
  successSoft: '#d1fae5',
  warning: colors.warning,
  warningSoft: colors.amberSoft,
  danger: colors.danger,
  dangerSoft: '#fee2e2',
  radiusSm: rounded.sm,
  radiusMd: rounded.md,
  radiusLg: rounded.lg,
  radiusFull: rounded.full,
  spaceXs: spacing.xs,
  spaceSm: spacing.sm,
  spaceMd: spacing.md,
  spaceBase: spacing.base,
  spaceLg: spacing.lg,
};

/** Dark: deep slate canvas, luminous accents */
export const darkPalette = {
  background: '#0c1222',
  surface: '#151d2e',
  surfaceSoft: '#1e293b',
  fillInput: '#1e293b',
  primary: '#818cf8',
  primarySoft: 'rgba(129, 140, 248, 0.18)',
  accent: '#38bdf8',
  coral: '#fb7185',
  coralSoft: 'rgba(251, 113, 133, 0.15)',
  mint: '#2dd4bf',
  mintSoft: 'rgba(45, 212, 191, 0.12)',
  iris: '#c4b5fd',
  irisSoft: 'rgba(167, 139, 250, 0.15)',
  amber: '#fbbf24',
  amberSoft: 'rgba(251, 191, 36, 0.12)',
  chipInactive: '#1e293b',
  text: '#f8fafc',
  textMuted: '#94a3b8',
  border: 'rgba(148, 163, 184, 0.12)',
  success: '#34d399',
  successSoft: 'rgba(52, 211, 153, 0.15)',
  warning: '#fbbf24',
  warningSoft: 'rgba(251, 191, 36, 0.12)',
  danger: '#f87171',
  dangerSoft: 'rgba(248, 113, 113, 0.15)',
  radiusSm: rounded.sm,
  radiusMd: rounded.md,
  radiusLg: rounded.lg,
  radiusFull: rounded.full,
  spaceXs: spacing.xs,
  spaceSm: spacing.sm,
  spaceMd: spacing.md,
  spaceBase: spacing.base,
  spaceLg: spacing.lg,
};

export const drawerWidth = 284;
